name: TopKill
api: 4.0.0
version: 1.0.0
main: FRashkar\TopKill\Loader
author: FRashkar-pm
commands:
  topkill:
    description: Open TopKillUI
    permission: topkill.use
    aliases:
    - tk
permissions:
  topkill.use:
    description: Allow you to use topkill!
    default: op